name: GitHub Secrets Demo

on:
  push:
    branches:
      - main

jobs:
  secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Use secret safely
        env:
          SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          echo "Secret is available in workflow"
          echo "Secret length is ${#SECRET_MESSAGE}"